# Generated by Django 4.0.4 on 2022-05-09 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_id_alter_device_info'),
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='devices', to='device.device'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
