# Generated by Django 4.0.4 on 2022-05-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('sate', models.CharField(blank=True, max_length=64)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_occupied', models.BooleanField(default=False)),
                ('installed_hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='hub.hub')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dwelling.location')),
            ],
        ),
    ]
