# Generated by Django 4.0.4 on 2022-05-09 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_hub_devices_alter_hub_id'),
        ('dwelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelling',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='installed_hub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='hub.hub'),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dwelling.location'),
        ),
    ]
